name: R

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install some packages
        run: sudo apt-get -y install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          renv::restore()
          install.packages('devtools')
        shell: Rscript {0}
      - name: Check
        run: |
          devtools::load_all()
          testthat::test_package('hundredfungo')
        shell: Rscript {0}
